#!/bin/bash

# This file is part of the quickbuild software package.
# 
# quickbuild is free software that is distributed under the free software
# foundation's GNU Affero General Public License (AGPL) version 3.
#
# For more information see the quickbuild package homepage at:
#   https://github.com/lanceman2/quickbuild
#
# You can get the latest version of this file from:
# 
#  https://raw.githubusercontent.com/lanceman2/quickbuild/master/examples/bootstrap_download/bootstrap
#
##############################################################################


# The tag can be "master" or a full git check-in hash in lower case hex
# like for example:
#tag=dc184319be9a272ffa4528f5bb5d0902f1edbbbb
tag=0.2
url=https://raw.githubusercontent.com/lanceman2/quickbuild/$tag/quickbuild.make

# If we wanted a particular file, so we checks it's sha512 sum.
# Run:
#
#    sha512sum quickbuild.make
#
# to get this long hex number

sha512sum=d72c983ea6e308312be9b2e2503c75\
4840c98b7d78f3b37c64c45d84fc844e0b4773e3\
3ad3addf8267d84ccc626ae0afb41530f46769f6\
584da279c7fd4519e3


function usage()
{
    cat <<EOF

  Usage: $0

  This bootstrap script downloads a make file from url:

     $url

  We call it bootstrap because you need this make file before
  you can configure and make this package.

EOF
    exit 1
}


[ "$1" = "--help" ] && usage
[ "$1" = "-h" ] && usage

set -ex

# Go to the directory there this script is.
cd $(dirname ${BASH_SOURCE[0]})


if [ -z "$*" ] && [ -e quickbuild.make ] ; then
    set +x
    cat <<EOF

  The file quickbuild.make exists.
  If you wish to regenerate it remove it first.
  Or run

      $0 -f

EOF
    exit 1
fi


# get the quickbuild.make file from the web
wget --no-check-certificate $url -O quickbuild.make

if [ -n "$sha512sum" ] ; then
    set +x
    # We wanted a particular file, so we checks it's sha512 sum.
    echo "$sha512sum  quickbuild.make" | sha512sum -c
    set -x
else
    set +x
    echo "The sha512sum of the downloaded file:"
    set -x
    sha512sum quickbuild.make
fi

